apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  namespace: default
  name: python-secret
spec:
  vaultAuthRef: default-ns-auth
  mount: "api-secrets"   # This should match the mount path in Vault
  type: kv-v2
  path: "python"    # Only use the secret name, NOT "data/python"
  refreshAfter: 10s
  destination:
    create: true
    name: python-secret
  rolloutRestartTargets:
  - kind: Deployment
    name: python-deployment