apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-secrets-creation-default-ns
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/NavabShariff/vault-argo-cd-test
    targetRevision: main
    path: vault-secrets
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true